Blikkenlijst update
ksrvnjord/app.main pull request #519
Opened 2024-05-12 21:19 UTC by PimVeefkind

2024-05-28 07:27 UTC, alexanderserraris requested changes
Er lijken nog errors voor te komen.

2024-05-28 07:27 UTC, alexanderserraris commented on lib/src/features/more/pages/blikken_lijst_page.dart
Bij het openen van de pagina komt er een error. 

<img width="1211" alt="image" src="https://github.com/ksrvnjord/app.main/assets/76075246/04714292-c53c-411e-8bfc-76c2baeb8d76">

2024-06-13 07:43 UTC, PimVeefkind commented on lib/src/features/more/pages/blikken_lijst_page.dart
dit is opgelost!

2024-06-13 07:43 UTC, PimVeefkind commented on lib/src/features/more/widgets/blikkenlijst_tab_content.dart
> +              if (index >= docs.length - (type == 'regulier' ? 1 : 15)) {
Dit is niet meer tenminste ik kon het nergens vinden.

2024-06-14 21:50 UTC, alexanderserraris approved these changes
Looks good to me! Heb wat verdere optimalisaties aangebracht

2024-06-14 21:51 UTC, merged